### ISSUE TITLE
minecraft crashes saying its something with the gravity mod

### ISSUE THREAD

**Issue by LHS240112** [Fusion-Flux/GravityChanger#70]
when i create/ join a world it crashes
error message:
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'net.minecraft.class_243 me.andrew.gravitychanger.api.GravityChangerAPI.getWorldVelocity(net.minecraft.class_1657)'
Crash report:
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2/16/24, 1:35 PM
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.class_243 me.andrew.gravitychanger.api.GravityChangerAPI.getWorldVelocity(net.minecraft.class_1657)'
	at qouteall.imm_ptl.core.compat.GravityChangerInterface$OnGravityChangerPresent.getWorldVelocity(GravityChangerInterface.java:118)
	at qouteall.imm_ptl.core.McHelper.getWorldVelocity(McHelper.java:762)
	at qouteall.imm_ptl.core.render.context_management.RenderStates.updatePreRenderInfo(RenderStates.java:116)
	at net.minecraft.class_757.handler$bil000$imm_ptl_core$onFarBeforeRendering(class_757.java:4567)
	at net.minecraft.class_757.method_3192(class_757.java)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at qouteall.imm_ptl.core.compat.GravityChangerInterface$OnGravityChangerPresent.getWorldVelocity(GravityChangerInterface.java:118)
	at qouteall.imm_ptl.core.McHelper.getWorldVelocity(McHelper.java:762)
	at qouteall.imm_ptl.core.render.context_management.RenderStates.updatePreRenderInfo(RenderStates.java:116)
	at net.minecraft.class_757.handler$bil000$imm_ptl_core$onFarBeforeRendering(class_757.java:4567)

-- Affected level --
Details:
	All players: 1 total; [class_746['CleaningSun8115'/229, l='ClientWorld minecraft:overworld', x=7.50, y=64.00, z=-1.50]]
	Chunk stats: Client Chunks (ImmPtl) 40
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,66,0), Section: (at 0,2,0 in 1,4,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 68 game time, 68 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 6182312896 bytes (5895 MiB) / 8002732032 bytes (7632 MiB) up to 26021462016 bytes (24816 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2486
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3758
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 49066.59
	Virtual memory used (MB): 29488.98
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 130.44
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx24816m -Xms256m
	Fabric Mods: 
		create: Create 0.5.1-c-build.1159+mc1.18.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.9-38
			forge_tags: Forge Tags 2.1
			forgeconfigapiport: Forge Config API Port 3.2.4
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			porting_lib: Porting Lib 1.2.1095-beta+1.18.2
				mm: Manningham Mills 2.3
				serialization_hooks: Serialization Hooks 0.3.23
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.11
		effortless: Effortless 2.1.0
		fabric-api: Fabric API 0.76.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.5+64b7c69360
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.7+e83becad60
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.13+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.3+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+43ce63a460
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.1.0+6c70b68e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.22+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.2+8165403660
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.16+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.7+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.5+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.5.0+bf48649860
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.1+03e2b68760
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.12+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.14+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.8+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+047a5ecb60
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.11+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.13+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		gravitychanger: GravityChanger 0.7.6
			cardinal-components-base: Cardinal Components API (base) 4.0.0
			cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		immersive_portals: Immersive Portals 1.4.10
			cloth-config: Cloth Config v6 6.2.57
				cloth-basic-math: cloth-basic-math 0.6.0
			imm_ptl_core: Immersive Portals Core 1.4.10
			q_misc_util: QMiscUtil 1.4.10
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.2
		pehkui: Pehkui 3.7.12+1.14.4-1.20.4
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.15.7-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 537.58, NVIDIA Corporation
	Window size: 1920x1200
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['CleaningSun8115'/229, l='ServerWorld minecraft:overworld New World', x=7.50, y=64.00, z=-1.50]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
mod list

![Screenshot 2024-02-16 133640](https://github.com/Fusion-Flux/Gravity-Api/assets/160240155/12bf06f5-bca4-468b-83ae-e11c581992d8)

**Comment by Fusion-Flux** [comment]
Unfortunately the 1.18.2 version of this mod was deemed too unstable and is now not maintained. the general issue appears to be that its unable to target some class.
